[build]
  # Change this from "ng build" to "npm run build"
  # This ensures it runs the script in package.json (node scripts/set-env.js && ng build)
  command = "npm run build" 
  publish = "dist/real-estate-dreamers/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200