[build]
  # This runs your script to generate environment.ts, then builds Angular
  command = "npm run build" 
  publish = "dist/real-estate-dreamers/browser"

[build.environment]
  # This tells Netlify: "I know my keys are public, please let me deploy."
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200